name: Deploy
on: push

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: actions/setup-node@v4
        with:
          deno-version: 22.x

      - name: Corepack enable
        run: corepack enable
      
      - name: Build
        run: pnpm build